# Generated by Django 3.1.6 on 2021-03-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Man',
            fields=[
                ('man', models.IntegerField(primary_key=True, serialize=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.emp')),
            ],
        ),
    ]
